language: cpp
branches:
  only:
    - master
    - devel
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  # this is going to break on osx, use a shell script?
  - sudo apt-get update -qq
  - sudo apt-get install -qq make
  - sudo apt-get install -qq gcc-multilib g++-multilib
  - sudo apt-get install -qq libuuid1 uuid-dev
  - mkdir -p deps/foundation && git clone https://github.com/origamicomet/foundation.git deps/foundation
script:
  - export FOUNDATION_CONFIG_CONFIGURATION=$GALA_CONFIG_CONFIGURATION
  - export FOUNDATION_CONFIG_LINKAGE=$GALA_CONFIG_LINKAGE
  - export FOUNDATION_CONFIG_ARCHITECTURE=$GALA_CONFIG_ARCHITECTURE
  - cd deps/foundation && ./configure && cd -
  - ./configure --foundation=deps/foundation
  - make all
rvm:
  - 1.9.3
env:
  global:
    - GALA_CONFIG_PARANOID=yes
  matrix:
    - GALA_CONFIG_CONFIGURATION=debug GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=development GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=release GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=debug GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=development GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=release GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86
    - GALA_CONFIG_CONFIGURATION=debug GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86-64
    - GALA_CONFIG_CONFIGURATION=development GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86-64
    - GALA_CONFIG_CONFIGURATION=release GALA_CONFIG_LINKAGE=static GALA_CONFIG_ARCHITECTURE=x86-64
    - GALA_CONFIG_CONFIGURATION=debug GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86-64
    - GALA_CONFIG_CONFIGURATION=development GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86-64
    - GALA_CONFIG_CONFIGURATION=release GALA_CONFIG_LINKAGE=dynamic GALA_CONFIG_ARCHITECTURE=x86-64
  allow_failures:
    - os: osx
cache:
  - apt
notifications:
  email:
    recipients:
      - developers@origamicomet.com
    on_success: change
    on_failure: always

